### ISSUE TITLE
Ok to create a behaviour with this?

### ISSUE THREAD

**Issue by zimme** [Q42/pending-changes#2]
Hey

I'm thinking I wanna do `zimme:collection-pending-changes` or something like that using my `zimme:collection-behaviours` package.

Why I'm asking is because you might prefer if I submit a PR to add this functionality into this package instead.

It will make the following possible

``` js
Posts = new Mongo.Collection('posts');
Posts.attachBehaviour('pending-changes');

Posts.pendingChanges(); // return changes.getTotal();

Posts.hasPendingChanges(); // return changes.getTotal() > 0

const post = Posts.findOne();

post.pendingChanges() // return changes.get(this._id);

post.hasPendingChanges() // return changes.get(this._id) > 0;
```

I would list this or the new package under the available behaviours section of `zimme:collection-behaviours`'s `README.md`

**Comment by zimme** [comment]
as a side note, I'm probably going to move my behaviour packages under the `behaviours` namespace when I get the time so it would then be `behaviours:core` and `behaviours:pending-changes`

**Comment by remcoder** [comment]
Hi Zimme,

Sorry to keep you waiting! I'm actually working on an update to change the api to just `Posts.hasPendingChanges()`, resulting in `true` or `false`. 

Also, I'm planning to extend the prototype of `Mongo.Collection` automatically when this package is added. 

Maybe it's best to see what this update will look like. It will have some similarities but also some differences with your proposal. 

In any case you're welcome to to re-use this code or create your own version as your own package.

I hope this answers your question somewhat. I hope to push the update in the next days or so when I get a change to get behind my laptop again ;-)

cheers,
Remco

**Comment by zimme** [comment]
:+1: I'll wait for the updated version and see where I'll go from there =)

**Comment by remcoder** [comment]
Hey Zimme,

Check the changes. Let me know what you think ;-)

**Comment by zimme** [comment]
Looks like the new behaviour is in the direction I was going with this too :+1:

I'll probably do a version of this for my `collectionbehaviours` "suite" but I'll ping you before releasing to see if and how I go about that. I have some ideas of using `dburles:collection-helpers` if available to register `hasPendingChanges` onto the returned documents from the collection. =)

**Comment by remcoder** [comment]
If you have any ideas about how to work around the requirement of having an _id when inserting, I'd like to know :-)

**Comment by zimme** [comment]
Don't have a solution for that... yet ;)

Also I'm pretty sure that if you don't provide a callback for the `insert`/`update`/`remove` actions the pending changes counter will decrease as soon as the document have been inserted/updated/removed from minimongo... pretty sure that's how `matb33:collection-hooks` works...

I think one might need to have that pending changes thing on server-side and publish the count to the client and use the published value for the logic client-side.

**Comment by remcoder** [comment]
hmm, thanks for pointing that out. I'll have to take a look at the collection-hooks code and maybe see if there are alternative solutions.

I don't think the tracking changes on the server and the publishing it on the client is preferable because the whole thing is meant to show the latency of the updates. Adding an extra round-trip will make the latency look worse than it is...

Thanks for your input. Much to chew on. I appreciate it ;-) And get back to you when I know more.

**Comment by zimme** [comment]
https://github.com/matb33/meteor-collection-hooks/blob/master/insert.js#L41-L50
That was what caught my eye =)
